# Generated by Django 2.0.1 on 2018-02-08 19:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Nazwa pytania', max_length=200, verbose_name='Nazwa')),
                ('questionText', models.TextField(default='Treść pytania', verbose_name='Pytanie')),
                ('testsText', models.TextField(default='', verbose_name='Testy')),
            ],
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Nazwa testu', max_length=200, verbose_name='Nazwa')),
                ('dateStart', models.DateTimeField(default=datetime.datetime.now, verbose_name='Data rozpoczęcia')),
                ('dateEnd', models.DateTimeField(default=datetime.datetime.now, verbose_name='Data zakończenia')),
            ],
        ),
        migrations.CreateModel(
            name='UserTestQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('testQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testerka.TestQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='UserTestSuite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currentQuestion', models.IntegerField(default=0)),
                ('finished', models.BooleanField(default=False)),
                ('testSuite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testerka.TestSuite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usertestquestion',
            name='userTestSuite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testerka.UserTestSuite'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='testSuite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testerka.TestSuite'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='testquestion',
            order_with_respect_to='testSuite',
        ),
    ]
