# Generated by Django 2.0.1 on 2018-02-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testerka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestquestion',
            name='answer',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='usertestsuite',
            name='currentQuestion',
            field=models.IntegerField(default=1),
        ),
    ]
